// <auto-generated />
namespace Car_Galery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class v100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v100));
        
        string IMigrationMetadata.Id
        {
            get { return "202007281932462_v1.0.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
